version: '3.8'

services:
  api-server:
    build:
      context: .
      dockerfile: dockerfiles/api.Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development

  node1:
    build:
      context: .
      dockerfile: dockerfiles/node.Dockerfile
    environment:
      - NODE_ID=node1
      - CPU_CORES=4
    depends_on:
      - api-server

  node2:
    build:
      context: .
      dockerfile: dockerfiles/node.Dockerfile
    command: ["python", "node.py", "--node-id", "node2", "--api-server", "http://api-server:5000", "--cpu-cores", "2"]
    depends_on:
      - api-server